#pragma once
// STRING owner. Included in ABI order by mapedit/runtime.hpp.
class STRING {
public:
    char* m_buf;
    static char EMPTY[16];
    STRING();
    STRING(const char* str);
    STRING(const char* str1,const char* str2);
    STRING(const char* str,int len);
    STRING(const STRING& r);
    STRING(const STRING* r);
    ~STRING();
    void Copy(const char* str, int len);
    char* CharPtr();
    int Length();
    int HaveChar(int chr);
    int WriteToBuf(void* buffer);
    char LastChar();
    void SetChar(int index,int c);
    int Replace(const STRING& source,const STRING& dest);
    int Replace(const STRING* source,const STRING* dest);
    int Replace(const char* source,const char* dest);
    STRING ToLower();
    STRING ToUpper();
    STRING ToBase64(int add_code);
    void RemoveBeginChars(const char* chars);
    void RemoveEndChars(const char* chars);
    void Read(FILE* file);
    void Read(STREAM* file);
    void Write(STREAM* file);
    void Write(FILE* file);
    int IsDigit();
    int Int();
    float Float();
    unsigned int FourCC();
    STRING BeforeChar(const char* chars) const;
    char operator[](int index);
    int LoadFile(const STRING& filename);
    int SaveFile(const STRING& filename) const;
    STRING Before(const char* marker) const;
    STRING After(const char* marker) const;
    STRING BeforeLast(const char* marker) const;
    const STRING AfterLast(const char* marker) const;
    char FirstChar() const;
    const STRING Add(int arg) const;
    int WriteToClipboard(HWND__* wnd);
    int ReadFromClipboard(HWND__* wnd);
    int HaveFirst(const char* prefix) const;
    int HaveSubStr(const char* str);
    void ToWideChar(unsigned short* buffer,int size_buffer);
    const STRING SplitRegPath(HKEY__** root) const;
    STRING operator+(const char* rhs) const;
    STRING operator+(const STRING& rhs) const;
    const STRING* operator+=(const char* rhs);
    const STRING* operator+=(const STRING* r);
    int operator==(const char* rhs);
    int operator!=(const char* rhs);
    int operator!=(const STRING* r);
    const STRING* operator=(const STRING& r);
    const STRING* operator=(const STRING* r);
    const STRING* operator=(const char* str);
    int operator==(const STRING* r);
    int operator<(const STRING* r);
    int operator>(const STRING* r);
};
const STRING __cdecl operator+(const char* lhs,const STRING& rhs);
static_assert(sizeof(STRING)==4, "MapEdit STRING size");
STRING __cdecl Printf(const char* format,...);

