#pragma once
// GRAPH_CORE/GRAPH owners. Included in ABI order by mapedit/runtime.hpp.
class GRAPH_CORE {
public:
    explicit GRAPH_CORE(const GRAPH_INIT* init);
    int Init(HWND__* hwnd);
    virtual void SetDefaultState();
    ~GRAPH_CORE();
    enum TYPE_SURFACE { S_PRIMARY=0, S_BACKBUFFER=1, S_TEXTURE=2, S_TEXTURE_SYSTEM=3, S_TEXTURE_DYNAMIC=4, S_ZBUFFER=5, S_ZBUFFER_SOFT=6, S_OFFSCREEN=7 };
    int PreTact();
    int BlitZBuffer();
    void ReLoadPalettes();
    void CheckDriverBugs();
    void RefreshBuffers();
    void* CreateSurface(int width,int height,TYPE_SURFACE type,const DDPIXELFORMAT_OLD* format);
    void* DDraw();
    void* D3DDevice();
    IDirectDrawSurface7* ZBufferSoft();
    HWND__* Wnd();
    void PostTact(int draw);
    void ClearScreen(COLOR color);
    void LockZ();
    void UnLock();
    void UnLockZ();
    void FlipToGDISurface();
    void SetViewPort(float x0,float y0,float x1,float y1);
    int RealZBuffer(float x,float y);
    int InViewPort(float x,float y);
    void* LockSurface(void* surface,int* pitch,RECT_OLD* rect);
    void Lock();
    int BytesPerPixel();
    void Error(int type,const char* text,unsigned long err);
    long SetRenderState(unsigned long state,unsigned long value);
    long CopyToZBuffer(RECT_OLD* screen_rect,RECT_OLD* tex_rect,TEXTURE* tex);
    void DrawPrimitive(unsigned long type,unsigned long vertexShader,void* vertex,unsigned int sizeOneVertex,int noVertex);
    void PutsXY(float x,float y,const char* str,COLOR color);
    void PutsXY(float x,float y,const STRING* str,COLOR color);
    void PutcXY(float x,float y,char c,COLOR color);
    void Effect(int eff,int var1,int var2,int duration);
    void SetFont(const STRING* font_name,int width,int height);
private:
    uint8_t opaque[0xC14]; // compiler vfptr + opaque = debug metadata 0xC18
};
static_assert(sizeof(GRAPH_CORE)==0xC18, "debug metadata GRAPH_CORE size");
class GRAPH : public GRAPH_CORE {
public:
    explicit GRAPH(const GRAPH_INIT* init);
    int Init(HWND__* hwnd);
    void SetDefaultState() override;
    ~GRAPH();
    static COLOR BLACK;
    static COLOR BLUE;
    static COLOR LIGHTBLUE;
    static COLOR RED;
    static COLOR GREEN;
    static COLOR GRAY;
    static COLOR LIGHTRED;
    static COLOR YELLOW;
    static COLOR WHITE;
    void UpdateStartupDialog(DIALOG_COMBO_BOX*,DIALOG_COMBO_BOX*,DIALOG_BUTTON*);
    void Lock();
    void* Lock(int* pitch);
    int BytesPerPixel();
    float ViewXMin(); float ViewYMin(); float ViewXMax(); float ViewYMax();
    int BoxInViewPort(float left,float top,float right,float bottom);
    float SizeX(); float SizeY();
    int IsPaused();
    int CapsFullScreen();
    int CapsNotPalette();
    int Is15Bit();
    RGB16 ColorIntensity(int intensity);
    void Tact(int draw);
    int DrawLoadBar(VID* draw_vid);
    void __cdecl DrawDebugText(const char* str,...);
    void OldLoadParameters(STREAM* res);
    void LoadParameters(STREAM* res);
    void DrawEffect(int draw);
    int GetEffectState(int effect);
    void DrawFog(float fx0,float fy0,float fx1,float fy1,int fogBottom,int fogTop,COLOR fogColor,unsigned short* table,int end,int invert);
    void DrawVid(VID* vid,int ncadr,float shiftx,float shifty,float shiftz);
    int DrawPicture(const STRING* filename,float x,float y);
    void DrawLightSource(float shiftx,float shifty,float shiftz,float size_x,float size_y,COLOR color);
    void DrawGroundSnow();
    void DrawRain();
    void DrawSnow();
    void __cdecl PrintfXY(float x,float y,const char* str,...);
    void Box(float x,float y,float xx,float yy,COLOR color);
    void Bar(float x,float y,float x1,float y1,COLOR color);
    void LightBar(float x,float y,float x1,float y1,unsigned int bright);
    long SetAlphaBlend(unsigned long srcBlend,unsigned long destBlend);
    void Line(float x,float y,float x1,float y1,COLOR color);
    void WuLine(float x0,float y0,float x1,float y1,COLOR color);
    void Circle(float xx,float yy,float radius,COLOR color);
    void PutAlphaPixel(float x,float y,COLOR color,unsigned int alpha);
    void PutPixel(float x,float y,COLOR color);
    void PutPixel(int x,int y,COLOR color);
    COLOR GetPixel(float x,float y);
    void SavePict(PICTURE* pict,int pict_x,int pict_y,int x,int y,int sizex,int sizey);
    void SavePictAndZ(PICTURE_MAKEVID* pict,int pict_x,int pict_y,int x,int y,int sizex,int sizey);
    void SaveTGA(const STRING* file,int x,int y,int sizex,int sizey);
    void SaveZ(const STRING* file,int x,int y,int sizex,int sizey);
    void PutBigPixel(float x,float y,COLOR color);
    void BeginPause();
    void EndPause();
    void LockZ();
    unsigned short* LockZ(int* pitch);
    GAMMA GetGamma();
    TEXTURE* AlphaBuffer();
    void SetGamma(const GAMMA* gamma);
    void DrawSquall();
    void ShadowLine(float x,float y,float x1,float y1,int shadow);
    void ShadowBar(float x,float y,float x1,float y1,int shadow);
    void LightLine(float x,float y,float x1,float y1,unsigned int bright);
    void StopMovie();
    void PlayMovie(const STRING* file);
    int IsPlayMovie();
    float WindSpeed();
    ANGLE WindDirection();
    int IsEnvironment(unsigned int environment);
    void SetWind(int speed,ANGLE direction);
    void SetEnvironment(unsigned int env);
    void SaveParameters(STREAM* res);
private:
    STRING debugText; // +0xC18
};
static_assert(sizeof(GRAPH)==0xC1C, "debug metadata GRAPH size");
